language: crystal
script:
  - crystal tool format --check
  - crystal docs
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: "docs"
    on:
      branch: master
